import { isProspect } from "./prospect.ts";
import { isKnownVoice } from "./voiceOptions.ts";
import { voiceCopy } from "./voiceCopy.ts";
import { deriveUseCases, type VoiceUseCases } from "./voiceUseCases.ts";
import type { CustomerProfile } from "./schema.ts";

/* =============================================================================
   voiceAgentSpec.ts — a prospect's own Qualify-and-Route configuration
   -----------------------------------------------------------------------------
   The voice workflow's CONTENT for one prospect: what the intent looks like, how the agent
   opens the call, the qualifying question and its answers, and the routing steps including
   the service-area check.

   ⚠️ **WHY AN OVERRIDE TABLE RATHER THAN GENERATED DATA.** Everything else on this screen is
   derived per prospect, and for most of them derivation is right — it costs no generation time
   and every demo on disk gets it. But an SE configuring a real agent types THESE words: the
   exact greeting, the exact ZIP codes, the exact sentence read to a caller outside the service
   area. Deriving those would be inventing them. Same pattern and same matcher as `SHAPE` and
   `SMS_SHAPE` in AgentWorkflow: keyed by prospect NAME through `isProspect`, never a guessed
   id, because these demos live in the shared library and their ids are whatever the SE typed.

   ⚠️ **EVERY PROSPECT NOW GETS THIS TEMPLATE (8/27/2026), DERIVED WHERE IT IS NOT CONFIGURED.**
   It used to return null for anyone but Comfort Keepers, and the consequence was measured
   across all 12 profiles on disk: 8 of them never asked for a ZIP and **11 never asked for a
   name**, while every one of them drew "Consumer Zip" and "Consumer Name" pills on the
   diagram. The tree advertised collecting two things the agent never collected, and nothing
   failed. `deriveVoiceSpec` closes that by building the same shape from the prospect's own
   profile, so a demo generated by any SE behaves like the configured one.

   ⚠️ **DERIVED, NOT GENERATED — no engine phase and no schema slice**, so generation time is
   unchanged and every demo already in the shared library gets it without regenerating.

   ⚠️ **AN EXPLICIT SPEC STILL WINS OUTRIGHT.** Where an SE typed the words, those are the
   words: `SPECS` is searched first and derivation only fills the gap.
   ============================================================================= */

/** The configured specs write the greeting as their last conversation rule; so does the
    derived one. `specWithConfig` finds it by this prefix to keep the copy in step. */
export const GREETING_RULE_PREFIX = "This is how you should also greet and start a phone call: ";

export interface VoiceAgentSpec {
  /** Matched with `isProspect`, so any id the SE typed still resolves. */
  prospect: string;
  /** "What does this intent look like?" — the description AND the opening line. */
  intent: string;
  /** What the agent says first. Also the last of the conversation rules, as the real one has it. */
  greeting: string;
  /** The Qualify leaf's question. */
  qualifyQuestion: string;
  /**
   * The branches under the two user-group nodes, one per USE CASE.
   *
   * ⚠️ **THIS REPLACED A FIXED PAIR OF SALES SEGMENTS (8/27/2026)**, at the user's request:
   * "those 2 can have as many branches as the user want, those branches represent use cases."
   * The old `segments: [string, string]` was a TUPLE, so the type itself made a third sales
   * branch impossible and the support node could not branch at all. Both limits were ours,
   * not the product's.
   */
  useCases: VoiceUseCases;
  /** What the agent says when it cannot tell which answer it heard. */
  qualifyFallback: string;
  /** The intent's conversation rules, in order. */
  rules: string[];
  /**
   * ⚠️ **AN ALLOW-LIST, WHICH INVERTS THE DEMO GATE.** The generic voice prompt treats a single
   * ZIP ("12345") as the only OUT-of-area one, so every other ZIP proceeds — right for a
   * national business. This prospect serves three ZIPs and turns everything else away, so the
   * polarity is the other way round and `buildVoiceSystem` has to be told which it is.
   */
  serviceZips?: string[];
  /** Read verbatim to a caller outside the service area. */
  outOfAreaScript?: string;
  /** The Inform & Route steps, verbatim, in the SE's own numbering. */
  informSteps: string[];
  /**
   * What the agent does when a caller needs the support team.
   *
   * ⚠️ IT WAS A LITERAL INSIDE `workflowDrawers.ts` UNTIL 9/21/2026, which meant the drawer
   * showed an instruction the PROMPT never carried — the drawer-describes-something-the-agent-
   * does-not shape this file records three times. Optional, defaulting to the same wording, so
   * an agent nobody has edited reads exactly as before.
   */
  escalateHandling?: string;
  /**
   * The SUPPORT intent's own description and conversation rules.
   *
   * ⚠️ BOTH WERE HARDCODED UNTIL 9/21/2026 — the description was a literal in
   * `workflowDrawers.ts` and the rules were a bare `[]` — so the Need Support drawer showed
   * five read-only boxes on the one page where the words ARE the prompt. Optional, and both
   * fall back to exactly what was hardcoded, so an untouched agent is byte-identical.
   */
  supportIntent?: string;
  supportRules?: string[];
  /**
   * Which voice the agent speaks with — a `VOICE_OPTIONS` id like "thalia".
   *
   * ⚠️ **NOT PART OF THE PROMPT, and that is why it lives here rather than in `ChatBrain`.**
   * `voiceSystemPrompt` turns a brain into words the agent says; a TTS voice is how it says
   * them. It rides to the worker beside `greeting` as a per-call operational field.
   * Absent means `DEFAULT_VOICE_ID`, which is the voice every demo already had.
   */
  voice?: string;
}

/**
 * COMFORT KEEPERS — in-home senior care, franchised, and the caller is usually a family
 * member rather than the person receiving care. Both halves of the qualifying question matter
 * to them: arranging care AND caregiver recruitment, which is why the intent covers job
 * seekers as well as clients.
 */
const COMFORT_KEEPERS: VoiceAgentSpec = {
  prospect: "comfort keepers",
  intent:
    "The caller is reaching out about Comfort Keepers' home care services, either as a prospective client or family member interested in arranging care for themselves or a loved one, or as a job seeker interested in becoming a caregiver/employee.\n\n"
    + "This is how you should also greet and start a phone call: Hi, thanks for calling Comfort Keepers, I'm here to help. Are you looking to arrange care services for yourself or a loved one, or are you interested in becoming a caregiver with us?",
  greeting:
    "Hi, thanks for calling Comfort Keepers, I'm here to help. Are you looking to arrange care services for yourself or a loved one, or are you interested in becoming a caregiver with us?",
  qualifyQuestion:
    "Are you interested in arranging care services, or are you looking to become a caregiver with us?",
  /* ⚠️ COMFORT KEEPERS KEEPS EXACTLY WHAT ITS SE CONFIGURED: two sales branches, NO support
     branches and NO named destinations, so its signed-off diagram and its call are unchanged.
     A configured spec is the words a human typed; the derived defaults below are what a
     prospect gets when nobody has typed any. If this account ever wants support branches,
     Ask AI adds them. */
  useCases: {
    sales: [
      { title: "Looking for care services", collect: ["Consumer Zip", "Consumer Name"] },
      { title: "Interested in becoming a caregiver", collect: ["Consumer Zip", "Consumer Name"] },
    ],
    support: [],
  },
  qualifyFallback:
    "I want to make sure I connect you with the right team. Are you looking to arrange care services for yourself or a loved one, or are you interested in becoming a caregiver with us?",
  rules: [
    "If the caller is a prospective client or family member inquiring about care services, acknowledge their situation warmly (e.g. \"I'd be happy to help you find the right care\") before asking any qualifying questions. Many callers are inquiring on behalf of an aging parent or family member and are dealing with a difficult situation.",
    "If the caller is inquiring about caregiver employment, respond professionally and briefly acknowledge that Comfort Keepers is always looking for compassionate caregivers before moving to next steps.",
    "As soon as this intent is recognized, determine whether the caller is looking to arrange care services or is interested in becoming a caregiver, so the conversation can proceed down the correct path.",
    "When asking for the caller's zip code, explain that it's used to connect them with their local Comfort Keepers office.",
    "If asked about cost or pricing, do not provide specific numbers. Acknowledge that pricing varies by service type and location, and let the caller know the local team will cover exact pricing.",
    GREETING_RULE_PREFIX + "Hi, thanks for calling Comfort Keepers, I'm here to help. Are you looking to arrange care services for yourself or a loved one, or are you interested in becoming a caregiver with us?",
  ],
  serviceZips: ["30097", "30096", "30095"],
  outOfAreaScript:
    "Thank you for calling Comfort Keepers. Unfortunately, we don't currently serve your area, but we'd encourage you to check back with us in the future or visit comfortkeepers.com to find a nearby location.",
  /* ⚠️ VERBATIM, INCLUDING THE ORDERING. Step 3 says to turn an out-of-area caller away and
     step 5 supplies the words for it, which reads out of sequence — but it is the SE's own
     configuration and tidying it would be editing their agent rather than replicating it. */
  informSteps: [
    "1. Ask the caller for their zip code and capture it.",
    "2. Check the zip code against our current service area: 30097, 30096, 30095.",
    "3. If the zip code falls outside 30097, 30096, or 30095, politely inform the caller that we do not yet serve their area and end the call.",
    "4. If the zip code falls within our service area, ask the caller for their full name and capture it.",
    "5. If zip code does not fall within our service area say: Thank you for calling Comfort Keepers. Unfortunately, we don't currently serve your area, but we'd encourage you to check back with us in the future or visit comfortkeepers.com to find a nearby location.",
    "6. If the caller does not provide their full name, ask again before proceeding. Do not route the call without a captured full name.",
  ],
};

const SPECS: VoiceAgentSpec[] = [COMFORT_KEEPERS];

/**
 * The same Qualify-and-Route template, built from a prospect's own profile.
 *
 * ⚠️ **THE WORDING IS DELIBERATELY IDENTICAL TO WHAT THE DIAGRAM ALREADY DREW.** `intent`'s
 * FIRST LINE is `newSub` and `segments` are the exact pair `deriveTree` used as its fallback,
 * because the tree renders `intent.split("\n")[0]` as the Sales Inquiry subtitle and renders
 * `segments` as the two path nodes. Any other phrasing here would silently reword every
 * existing prospect's diagram, which is a change to screens nobody asked about.
 *
 * ⚠️ **ZIP CODES ARE NEVER INVENTED.** Comfort Keepers' three are an SE's own configuration.
 * Minting a plausible-looking allow-list for a real company would put fabricated service
 * areas in front of that company, and a caller ZIP outside it would be turned away for a
 * reason that does not exist. So `serviceZips` stays undefined here and the gate falls back to
 * the prospect's generated `serviceArea`: a real constraint when it has one, and a routing
 * lookup rather than a refusal when it does not.
 */
export function deriveVoiceSpec(profile: CustomerProfile): VoiceAgentSpec {
  const c = voiceCopy(profile);
  const name = profile.customerName;
  const area = profile.reports.agentConfig?.serviceArea?.trim();
  /* ⚠️ **`brandConversationRules` IS THE *SMS* SALES PLAYBOOK AND MUST NOT REACH THIS PROMPT.**
     The Intent drawer used to append three of them here, which was invisible while the spec
     was Comfort-Keepers-only. The moment every prospect got a spec they also reached the voice
     agent, and they read like "Qualify one at a time: ... your target price or monthly payment,
     your timeline to buy" — directly contradicting the flow's own "ASK NOTHING BEYOND THE FLOW
     ABOVE" cap. That is the over-asking already fixed once for Comfort Keepers, and a
     self-contradicting prompt is worse than either rule (see CLAUDE.md). The configured spec
     carries none of them, so deriving none is also what makes the two shapes agree.

     CONSEQUENCE, STATED: a non-configured prospect's Intent drawer now shows three rules
     rather than six. The three it loses were SMS playbook lines rendered as voice-workflow
     rules, which was wrong on that screen too. */

  const cases = deriveUseCases(profile);
  const booking = (profile.bookingTerm || "Reservation").toLowerCase();
  const an = /^[aeiou]/i.test(booking) ? "an" : "a";
  /* ⚠️⚠️ **THE OPENING QUESTION SPLITS ON INTENT, NOT ON USE CASE — and reading the branches
     aloud was a real mistake worth recording.** A first version built it from the sales
     branch titles, which sounds principled (the question can then never offer something the
     diagram does not draw) and produced, verbatim: "Are you ready to book now, comparing
     options or group or event booking, or do you need help with something already in
     progress?" Nobody says that on a phone.

     The tree already answers this: the row the caller is being sorted into at the OPENING is
     Sales Inquiry vs Need Support. The use cases are the row BELOW, classified from what they
     go on to say — which is exactly what the CALL FLOW block lists for the model. So the
     question stays two-way and speakable, and the branches never have to be recited. */
  const greeting =
    `Hi, thanks for calling ${name}. I'm here to help. Are you looking to book ${an} ${booking}, `
    + `or do you need help with one you already have?`;

  /* ⚠️ THE GREETING IS ALSO THE LAST CONVERSATION RULE, exactly as the configured spec has it,
     so the drawer and the spoken opening cannot drift apart. */
  const greetingRule = `${GREETING_RULE_PREFIX}${greeting}`;

  return {
    prospect: name,
    /* Line 1 is the diagram's subtitle. Everything after it is drawer and prompt detail. */
    intent:
      `${c.newSub}\n\n`
      + `Treat them as a prospective ${c.who} and find out what they need before routing.\n\n`
      + greetingRule,
    greeting,
    qualifyQuestion:
      `Are you looking to book ${an} ${booking}, or do you need help with one you already have?`,
    useCases: cases,
    qualifyFallback:
      `I want to make sure I connect you with the right team. Are you looking to book ${an} ${booking}, `
      + `or do you need help with one you already have?`,
    rules: [
      ...(area
        ? [`When asking for the caller's zip code, explain that it is used to connect them with their local ${name} office.`]
        : [`When asking for the caller's zip code, explain that it is used to connect them with their nearest ${name} location.`]),
      `As soon as this intent is recognized, find out what the caller needs so the conversation can proceed down the correct path.`,
      `If asked about cost or pricing, do not provide specific numbers. Acknowledge that pricing varies and let the caller know the local team will cover exact pricing.`,
      greetingRule,
    ],
    /* Never invented. See the note above. */
    serviceZips: undefined,
    outOfAreaScript: area
      ? `Thank you for calling ${name}. Unfortunately we do not currently serve your area. ${name} serves ${area}.`
      : undefined,
    /* ⚠️⚠️ **THE STEPS ARE THE SERVICE-AREA GATE, NOT A FIELD LIST (8/27/2026).** They used to
       spell out "ask for the zip, then the full name", which was right while every branch
       collected the same two things. The moment each use case carries its OWN fields the two
       contradict — Marriott's "Ready to book now" wants Destination and Travel Dates, not a
       caller's home ZIP — and `buildVoiceSystem` prefers the STEPS, so the branches would have
       been silently ignored. The fields now come from the branch the caller picked; the steps
       cover only the thing no branch can express, which is whether this prospect turns
       out-of-area callers away.

       ⚠️ A NATIONAL PROSPECT THEREFORE GETS NO STEPS AT ALL, and that is deliberate rather
       than an omission: with no gate to describe there is nothing here that the call flow does
       not already say, and an extra instruction is one more thing to contradict. */
    informSteps: area
      ? [
          `1. Before routing anyone who wants new service, ask for their zip code and capture it.`,
          `2. Check it against our service area: ${area}.`,
          `3. If the caller is outside that service area, politely inform them and end the call without routing.`,
          `4. If they are inside it, briefly confirm we serve their area and continue with the questions for their path.`,
        ]
      : [],
  };
}

/** This prospect's voice-agent spec: the SE's own where one is configured, else derived. */
export function voiceSpecFor(profile: CustomerProfile): VoiceAgentSpec {
  return SPECS.find((s) => isProspect(profile, s.prospect)) ?? deriveVoiceSpec(profile);
}

/* =============================================================================
   THE AI-EDITABLE SLICE OF A VOICE AGENT
   -----------------------------------------------------------------------------
   ⚠️ **THIS IS EXACTLY THE PART THE DIAGRAM CANNOT DRAW.** The workflow page registers it
   beside the tree so one Ask AI instruction can build the routing AND configure the agent.
   The split is the whole design and it is not arbitrary:

     on the diagram  -> the tree owns it   (intent subtitle, leaf titles, path titles, chips)
     not on the diagram -> `agent` owns it (greeting, rules, ZIP allow-list, routing steps)

   ⚠️ **`segments` IS DELIBERATELY ABSENT.** The two answers under Qualify are DRAWN as path
   nodes, so the tree already owns them; a second copy here would mean an edit to one silently
   disagreeing with the other, which is the exact drift `voicePaths.ts` exists to prevent.
   Change the answers by editing the path nodes.

   ⚠️ **`intent` IS ABSENT TOO, and for a different reason:** its first line is the Sales
   Inquiry node's subtitle, and that node is product chrome the real page does not let anyone
   rename (`locked: true`, enforced by `editGuard.isLockedEdit`). Offering it here would be
   offering an edit the guard then refuses.
   ============================================================================= */
export interface VoiceAgentConfig {
  greeting: string;
  /** A `VOICE_OPTIONS` id. Validated on read, because this object is AI-writable. */
  voice?: string;
  qualifyQuestion: string;
  qualifyFallback: string;
  rules: string[];
  serviceZips?: string[];
  outOfAreaScript?: string;
  informSteps: string[];
  /**
   * What the agent does when a caller needs the support team.
   *
   * ⚠️ IT WAS A LITERAL IN `workflowDrawers.ts` UNTIL 9/21/2026 — so the drawer showed the
   * agent an instruction nobody had actually told it. Giving it a home both fixes that and
   * makes the field editable without becoming a dead control. Optional, and it falls back to
   * the same wording, so an agent nobody has edited is byte-identical.
   */
  escalateHandling?: string;
  supportIntent?: string;
  supportRules?: string[];
}

/** The editable slice of a spec, for registering as page data. */
/** The wording the escalate leaf has always shown. ONE definition, read by the drawer and the
 *  prompt, so the two cannot drift. */
/** The Need Support intent's description — ONE definition, read by the drawer and the prompt. */
export const DEFAULT_SUPPORT_INTENT =
  "Contacts seeking help with an existing product or service, such as troubleshooting, billing questions, or account changes.";
export const DEFAULT_ESCALATE_HANDLING =
  "Do not attempt to resolve the caller's question. Immediately let the caller know you're connecting them with a member of the support team, then transfer the call.";

export function agentConfigOf(spec: VoiceAgentSpec): VoiceAgentConfig {
  return {
    greeting: spec.greeting,
    qualifyQuestion: spec.qualifyQuestion,
    qualifyFallback: spec.qualifyFallback,
    rules: spec.rules,
    /* ⚠️ OMIT rather than write `undefined`. `editGuard` treats undefined -> value as a TYPE
       FLIP and blocks it unless the path is creatable, and a key present with an undefined
       value also serialises into the model's DATA as `null`, which reads as "this prospect
       has an empty allow-list" rather than "it has none". */
    ...(spec.serviceZips?.length ? { serviceZips: spec.serviceZips } : {}),
    ...(spec.outOfAreaScript ? { outOfAreaScript: spec.outOfAreaScript } : {}),
    informSteps: spec.informSteps,
    escalateHandling: spec.escalateHandling ?? DEFAULT_ESCALATE_HANDLING,
    supportIntent: spec.supportIntent ?? DEFAULT_SUPPORT_INTENT,
    supportRules: spec.supportRules ?? [],
    /* Omitted when unset, for the same reason as the two above: a key present with an
       undefined value serialises to the model as `null`, which reads as "this prospect has
       no voice" rather than "it has not chosen one". */
    ...(spec.voice ? { voice: spec.voice } : {}),
  };
}


/**
 * The routing steps for a ZIP allow-list.
 *
 * ⚠️ **THIS EXISTS BECAUSE `serviceZips` AND `informSteps` CAN CONTRADICT EACH OTHER, AND THE
 * STEPS WIN.** `buildVoiceSystem` renders the SE's own steps in preference to the allow-list
 * gate, which is right (they are the words a human typed). But when Ask AI was asked to "only
 * serve 90210 and 90211" it correctly wrote `agent.serviceZips` and left the derived steps
 * saying "Do not turn anyone away on their zip code. AutoNation takes enquiries nationally."
 * The prompt then followed the steps, the allow-list was never applied, and the drawer
 * reported success — an instruction that visibly landed and did nothing.
 */
/**
 * Coerce whatever the model wrote for `informSteps` into the `string[]` the prompt needs.
 *
 * ⚠️⚠️ **THIS EXISTS BECAUSE A `typeof r === "string"` FILTER SILENTLY ATE A CORRECT EDIT.**
 * Told that Avi & Co has three showrooms and to offer the nearest one when a caller's ZIP is
 * outside them, the model wrote two GOOD steps — naming Miami, New York and Aspen and
 * describing the fallback exactly as asked — as OBJECTS: `{step, action, description}`. The
 * filter dropped both for not being strings, `informSteps` became `[]`, and because the base
 * spec's steps are also `[]` the `stepsUntouched` comparison below then concluded nobody had
 * touched them and regenerated the stock refusal. The SE watched the diagram and the drawer
 * update and heard the agent turn callers away.
 *
 * `editGuard` cannot catch this: `agent.informSteps` is a LENGTH_IS_CONTENT path and
 * array -> array is not a type flip, so the write is legitimately allowed. The shape has to be
 * accepted HERE. Dropping data because it arrived in a reasonable-but-different shape is the
 * silent-no-op failure this file already records three times.
 */
export function toSteps(v: unknown, fallback: string[]): string[] {
  if (!Array.isArray(v)) return fallback;
  const out = v.map((r) => {
    if (typeof r === "string") return r.trim();
    if (r && typeof r === "object") {
      const o = r as Record<string, unknown>;
      /* Render the object the way the prompt reads a step: an imperative, then its detail. */
      const parts = [o.action, o.description, o.text, o.step_description]
        .filter((x): x is string => typeof x === "string" && !!x.trim())
        .map((x) => x.trim());
      if (!parts.length) return "";
      const n = typeof o.step === "number" || typeof o.step === "string" ? `${o.step}. ` : "";
      return `${n}${parts.join(": ")}`;
    }
    return "";
  }).filter(Boolean);
  /* Nothing survived normalisation — keep the base rather than returning an empty list, which
     is what turned "the agent stopped asking for a name" into a silent regression before. */
  return out.length ? out : fallback;
}

export function stepsForZips(zips: string[], script: string): string[] {
  const list = zips.join(", ");
  /* ⚠️⚠️ **THE SCRIPT IS THE ONLY OUT-OF-AREA POLICY — do not also hardcode a refusal.** This
     used to say "inform the caller that we do not serve their area and end the call without
     routing" in step 3 AND append the script in step 5. When the script REFUSES those agree;
     when it offers an alternative they flatly contradict each other, with the refusal first.
     Measured on Avi & Co: step 3 ended the call while step 5 offered the nearest showroom, and
     the agent obeyed step 3 — so an SE who asked for the nearest-showroom behaviour got a
     hang-up. A self-contradicting prompt is worse than either rule, which this repo has
     already paid for once with the SMS playbook leaking into the voice prompt.
     Whether we turn the caller away or offer them another location is now expressed in ONE
     place, and no prose is sniffed to decide which it is. */
  return [
    `1. Ask the caller for their zip code and capture it.`,
    `2. Check the zip code against our current service area: ${list}.`,
    `3. If the zip code falls outside ${list}, say: ${script}`,
    `4. Then follow the caller's answer. Do not route the call anywhere the caller has not agreed to.`,
    `5. If the zip code falls within our service area, ask the caller for their full name and capture it.`,
    `6. If the caller does not provide their full name, ask again before proceeding. Do not route the call without a captured full name.`,
  ];
}

/** A spec with the page's (possibly AI-edited) config laid over it. */
export function specWithConfig(spec: VoiceAgentSpec, cfg: VoiceAgentConfig | undefined): VoiceAgentSpec {
  if (!cfg) return spec;
  /* ⚠️ FIELD BY FIELD, NOT A SPREAD. A spread would let a partial or malformed override drop
     `informSteps` entirely and silently return the agent to not asking for a name. */
  const merged = {
    ...spec,
    greeting: typeof cfg.greeting === "string" && cfg.greeting.trim() ? cfg.greeting : spec.greeting,
    qualifyQuestion: typeof cfg.qualifyQuestion === "string" && cfg.qualifyQuestion.trim() ? cfg.qualifyQuestion : spec.qualifyQuestion,
    qualifyFallback: typeof cfg.qualifyFallback === "string" && cfg.qualifyFallback.trim() ? cfg.qualifyFallback : spec.qualifyFallback,
    rules: Array.isArray(cfg.rules) ? cfg.rules.filter((r) => typeof r === "string" && r.trim()) : spec.rules,
    serviceZips: Array.isArray(cfg.serviceZips)
      ? cfg.serviceZips.map((z) => String(z).trim()).filter(Boolean)
      : spec.serviceZips,
    outOfAreaScript: typeof cfg.outOfAreaScript === "string" && cfg.outOfAreaScript.trim()
      ? cfg.outOfAreaScript : spec.outOfAreaScript,
    informSteps: toSteps(cfg.informSteps, spec.informSteps ?? []),
    /* A non-empty string only; an emptied field falls back rather than leaving the agent with
       no escalation instruction at all — the same rule `toSteps` follows for the steps. */
    escalateHandling: (typeof cfg.escalateHandling === "string" && cfg.escalateHandling.trim())
      ? cfg.escalateHandling : (spec.escalateHandling ?? DEFAULT_ESCALATE_HANDLING),
    supportIntent: (typeof cfg.supportIntent === "string" && cfg.supportIntent.trim())
      ? cfg.supportIntent : (spec.supportIntent ?? DEFAULT_SUPPORT_INTENT),
    /* ⚠️ AN EMPTIED RULE LIST IS A REAL STATE HERE, unlike the strings above: the support
       intent ships with none, so "remove them all" has to mean none rather than falling back
       to a default the SE just cleared. */
    supportRules: Array.isArray(cfg.supportRules)
      ? cfg.supportRules.filter((r) => typeof r === "string" && r.trim())
      : spec.supportRules,
    /* ⚠️ VALIDATED, NOT TRUSTED. This object is the workflow page's Ask AI scope, so the
       model can write `agent.voice` — and an invented id would reach the worker and produce
       a call that connects and never speaks. An unknown value falls back to the spec's own,
       so the worst case is the voice not changing rather than the agent losing its tongue. */
    voice: isKnownVoice(cfg.voice) ? cfg.voice!.trim().toLowerCase() : spec.voice,
  };

  /* ⚠️ REPAIR THE ONE CONTRADICTION THE TWO FIELDS CAN HOLD. If a ZIP allow-list was added
     and the steps were NOT touched in the same edit, the steps still describe the old policy
     and would be obeyed instead. Regenerating only when the steps are byte-identical to the
     base keeps this narrow: the moment an SE (or the model) writes their own steps, those are
     the words and nothing rewrites them. */
  /* ⚠️ **THE GREETING IS COPIED INTO `rules`, AND A COPY GOES STALE.** Both the configured and
     the derived spec end their rules with "This is how you should also greet...", mirroring how
     an SE actually writes it on the real page. So changing ONLY `agent.greeting` left the rule
     still reciting the old opening — and the agent spoke the new greeting and then obeyed the
     old rule's question. Observed live: it opened "Thanks for calling AutoNation, this is Max."
     and immediately asked the previous "book a test drive" question.

     Narrow on purpose: only when the greeting actually changed, so a rule somebody rewrote by
     hand is never overwritten. */
  if (merged.greeting !== spec.greeting) {
    merged.rules = merged.rules.map((r) =>
      r.startsWith(GREETING_RULE_PREFIX) ? `${GREETING_RULE_PREFIX}${merged.greeting}` : r);
  }

  const zipsAdded = (merged.serviceZips?.length ?? 0) > 0 && !(spec.serviceZips?.length ?? 0);
  const stepsUntouched = JSON.stringify(merged.informSteps) === JSON.stringify(spec.informSteps);
  if (zipsAdded && stepsUntouched) {
    return {
      ...merged,
      informSteps: stepsForZips(
        merged.serviceZips ?? [],
        merged.outOfAreaScript
          ?? `Thank you for calling ${merged.prospect}. Unfortunately we do not currently serve your area.`,
      ),
    };
  }
  return merged;
}
